In [1]:
import numpy as np

In [2]:
# prior P([0, 1])
P = np.asarray([0.4, 0.6])
# transition P(X_t|X_(t_1))
Q = np.asarray([[0.9, 0.1], [0.2, 0.8]])
# observation P(O_t|X_t)
O = np.asarray([[0.6, 0.4], [0.3, 0.7]])

In [3]:
def filter_prob(pfp, Q, O, o):
    s = O[:,o]*(Q[0]*pfp[0] + Q[1]*pfp[1])
    return s/s.sum()

In [4]:
def forward_message(pm, Q, O, o):
    m = O[:, o]*(Q[0]*pm[0] + Q[1]*pm[1])
    return m

In [5]:
p0 = P

In [6]:
p0

array([0.4, 0.6])

In [7]:
# day 1, observation = 1
o = 1
p1 = filter_prob(p0, Q, O, o)
p1

array([0.34532374, 0.65467626])

In [8]:
np.asarray([48, 91])/(48+91)

array([0.34532374, 0.65467626])

In [9]:
# day 2, observation = 1
o = 1
p2 = filter_prob(p1, Q, O, o)
p2

array([0.31135903, 0.68864097])

In [11]:
np.asarray([307, 679])/(307+679)

array([0.31135903, 0.68864097])

In [12]:
# day 3, observation = 0
o = 0
p3 = filter_prob(p2, Q, O, o)
p3

array([0.58951434, 0.41048566])

In [25]:
8242/(8242+5739)

0.5895143408912095

In [49]:
p = P
print(p)
observations=[1, 1, 0, 0]
for o in observations:
    p = filter_prob(p, Q, O, o)
    print(o, p)

[0.4 0.6]
1 [0.34532374 0.65467626]
1 [0.31135903 0.68864097]
0 [0.58951434 0.41048566]
0 [0.75981301 0.24018699]


In [50]:
a=85656
b=27077
a/(a+b)

0.7598130095003238

In [51]:
n=a
[ d for d in range(2,int(math.sqrt(n))) if n % d == 0 ]

[2, 3, 4, 6, 8, 12, 24, 43, 83, 86, 129, 166, 172, 249, 258]

In [52]:
n=b
[ d for d in range(2,int(math.sqrt(n))) if n % d == 0 ]

[]

In [53]:
def predict_prob(pfp, Q, future_steps):
    p = pfp
    for _ in range(future_steps):
        p = (p[0]*Q[0] + p[1]*Q[1])
        p = p/p.sum()
    return p

In [54]:
p = P
print(p)
observations=[1, 1, 0, 0]
for o in observations:
    p = filter_prob(p, Q, O, o)
    print(o, p)

p = predict_prob(p, Q, 1)
print(p)

[0.4 0.6]
1 [0.34532374 0.65467626]
1 [0.31135903 0.68864097]
0 [0.58951434 0.41048566]
0 [0.75981301 0.24018699]
[0.73186911 0.26813089]


In [58]:
a=825058
b=302272
a/(a+b)

0.7318691066502266

In [64]:
b/(a+b)

0.26813089334977336

In [59]:
n=a
[ d for d in range(2,int(math.sqrt(n))) if n % d == 0 ]

[2, 13, 26, 169, 338]

In [60]:
n=b
[ d for d in range(2,int(math.sqrt(n))) if n % d == 0 ]

[2, 4, 8, 16, 32, 64]

In [30]:
p = P
print(p)
observations=[1, 1, 0, 0]
for o in observations:
    p = filter_prob(p, Q, O, o)
    print(o, p)

for _ in range(20):
    p = predict_prob(p, Q, 3)
    print(p)

[0.4 0.6]
1 [0.34532374 0.65467626]
1 [0.31135903 0.68864097]
0 [0.58951434 0.41048566]
0 [0.75981301 0.24018699]
[0.69861586 0.30138414]
[0.67762524 0.32237476]
[0.67042546 0.32957454]
[0.66795593 0.33204407]
[0.66710888 0.33289112]
[0.66681835 0.33318165]
[0.66671869 0.33328131]
[0.66668451 0.33331549]
[0.66667279 0.33332721]
[0.66666877 0.33333123]
[0.66666739 0.33333261]
[0.66666691 0.33333309]
[0.66666675 0.33333325]
[0.6666667 0.3333333]
[0.66666668 0.33333332]
[0.66666667 0.33333333]
[0.66666667 0.33333333]
[0.66666667 0.33333333]
[0.66666667 0.33333333]
[0.66666667 0.33333333]


In [37]:
def backward_message(pbm, Q, O, o):
    m = Q[:, 0]*O[0][o]*pbm[0] + Q[:, 1]*O[1][o]*pbm[1]
    return m/m.sum()

In [38]:
observations=[1, 1, 0, 0]
fps = []
bms = []

p = P

for o in observations:
    p = filter_prob(p, Q, O, o)
    fps.append(p)

    
m = [1, 1]
bms.append(m)
for o in observations[::-1]:
    m = backward_message(m, Q, O, o)
    bms.append(m)

bms.reverse()

sps = np.asarray(fps)*np.asarray(bms[1:])

sps = sps / sps.sum(1).reshape(-1,1)

In [39]:
from pprint import pprint

In [40]:
pprint(list(zip(observations, fps)))

[(1, array([0.34532374, 0.65467626])),
 (1, array([0.31135903, 0.68864097])),
 (0, array([0.58951434, 0.41048566])),
 (0, array([0.75981301, 0.24018699]))]


In [41]:
pprint(list(zip(observations, sps)))

[(1, array([0.37117792, 0.62882208])),
 (1, array([0.48201503, 0.51798497])),
 (0, array([0.69455262, 0.30544738])),
 (0, array([0.75981301, 0.24018699]))]


In [48]:
78299/(78299+34434)

0.6945526154719559

In [71]:
m = np.matrix([[0.9, 0.2], [0.1, 0.8]])

In [72]:
np.linalg.eig(m)

(array([1. , 0.7]),
 matrix([[ 0.89442719, -0.70710678],
         [ 0.4472136 ,  0.70710678]]))

In [73]:
m

matrix([[0.9, 0.2],
        [0.1, 0.8]])