In [1]:
from collections import Counter
import numpy as np
from pprint import pprint
from sklearn.datasets import fetch_20newsgroups

In [68]:
cats = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']

In [69]:
train_data = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'), categories=cats)

In [70]:
test_data = fetch_20newsgroups(subset='test', remove=('headers', 'footers', 'quotes'), categories=cats)

In [71]:
train_data.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [72]:
train_data.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [73]:
print(train_data.data[2])

(Well, I'll email also, but this may apply to other people, so
I'll post also.)



Your boss should be the person bring these problems to.  If he/she
does not seem to take any action, keep going up higher and higher.
Sexual harrassment does not need to be tolerated, and it can be an
enormous emotional support to discuss this with someone and know that
they are trying to do something about it.  If you feel you can not
discuss this with your boss, perhaps your company has a personnel
department that can work for you while preserving your privacy.  Most
companies will want to deal with this problem because constant anxiety
does seriously affect how effectively employees do their jobs.

It is unclear from your letter if you have done this or not.  It is
not inconceivable that management remains ignorant of employee
problems/strife even after eight years (it's a miracle if they do
notice).  Perhaps your manager did not bring to the attention of
higher ups?  If the company indeed does seem t

In [74]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [75]:
#vectorizer = CountVectorizer(min_df = 5, binary = True)
vectorizer = TfidfVectorizer(min_df = 5)

In [76]:
X_train = vectorizer.fit_transform(train_data.data)

In [77]:
X_train.shape

(2257, 5903)

In [79]:
#vectorizer.get_feature_names()

In [80]:
y_train = train_data.target

In [81]:
X_test = vectorizer.transform(test_data.data)

In [82]:
X_test.shape

(1502, 5903)

In [83]:
y_test = test_data.target

In [84]:
from sklearn.naive_bayes import BernoulliNB

In [85]:
bnb = BernoulliNB(alpha=1)

In [86]:
bnb.fit(X_train, y_train)

BernoulliNB(alpha=1)

In [87]:
y_train_pred = bnb.predict(X_train)

In [88]:
y_test_pred = bnb.predict(X_test)

In [89]:
from sklearn.metrics import confusion_matrix, accuracy_score, \
                            precision_score, recall_score, f1_score, classification_report

In [90]:
bnb.classes_

array([0, 1, 2, 3], dtype=int64)

In [91]:
train_data.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [92]:
Counter(y_train)

Counter({1: 584, 3: 599, 2: 594, 0: 480})

In [93]:
Counter(y_train_pred)

Counter({1: 983, 3: 438, 0: 406, 2: 430})

In [94]:
confusion_matrix(y_train, y_train_pred)

array([[316, 124,   3,  37],
       [  0, 578,   1,   5],
       [  6, 159, 423,   6],
       [ 84, 122,   3, 390]], dtype=int64)

In [95]:
Counter(y_test)

Counter({2: 396, 0: 319, 3: 398, 1: 389})

In [96]:
Counter(y_test_pred)

Counter({2: 236, 1: 725, 0: 247, 3: 294})

In [97]:
confusion_matrix(y_test, y_test_pred)

array([[137, 107,   8,  67],
       [  3, 368,   9,   9],
       [ 16, 156, 218,   6],
       [ 91,  94,   1, 212]], dtype=int64)

In [98]:
print(classification_report(y_train, y_train_pred, digits=3, target_names=train_data.target_names))

                        precision    recall  f1-score   support

           alt.atheism      0.778     0.658     0.713       480
         comp.graphics      0.588     0.990     0.738       584
               sci.med      0.984     0.712     0.826       594
soc.religion.christian      0.890     0.651     0.752       599

              accuracy                          0.756      2257
             macro avg      0.810     0.753     0.757      2257
          weighted avg      0.813     0.756     0.760      2257



In [99]:
print(classification_report(y_test, y_test_pred, digits=3, target_names=train_data.target_names))

                        precision    recall  f1-score   support

           alt.atheism      0.555     0.429     0.484       319
         comp.graphics      0.508     0.946     0.661       389
               sci.med      0.924     0.551     0.690       396
soc.religion.christian      0.721     0.533     0.613       398

              accuracy                          0.623      1502
             macro avg      0.677     0.615     0.612      1502
          weighted avg      0.684     0.623     0.618      1502



In [100]:
from sklearn.naive_bayes import MultinomialNB

In [137]:
mnb = MultinomialNB(alpha=1)

In [138]:
mnb.fit(X_train, y_train)

MultinomialNB(alpha=1)

In [139]:
y_train_pred = mnb.predict(X_train)

In [140]:
y_test_pred = mnb.predict(X_test)

In [141]:
print(classification_report(y_train, y_train_pred, digits=3, target_names=train_data.target_names))

                        precision    recall  f1-score   support

           alt.atheism      0.993     0.631     0.772       480
         comp.graphics      0.962     0.945     0.953       584
               sci.med      0.982     0.928     0.954       594
soc.religion.christian      0.725     0.988     0.836       599

              accuracy                          0.885      2257
             macro avg      0.915     0.873     0.879      2257
          weighted avg      0.911     0.885     0.884      2257



In [142]:
print(classification_report(y_test, y_test_pred, digits=3, target_names=train_data.target_names))

                        precision    recall  f1-score   support

           alt.atheism      0.922     0.260     0.406       319
         comp.graphics      0.910     0.882     0.896       389
               sci.med      0.909     0.780     0.840       396
soc.religion.christian      0.547     0.955     0.695       398

              accuracy                          0.742      1502
             macro avg      0.822     0.719     0.709      1502
          weighted avg      0.816     0.742     0.724      1502



In [143]:
from sklearn.linear_model import LogisticRegression

In [205]:
lr = LogisticRegression(penalty='l2', solver='lbfgs', C=10, multi_class='ovr')

In [206]:
lr.fit(X_train, y_train)

LogisticRegression(C=10, multi_class='ovr')

In [207]:
y_train_pred = lr.predict(X_train)

In [208]:
y_test_pred = lr.predict(X_test)

In [209]:
print(classification_report(y_train, y_train_pred, digits=3, target_names=train_data.target_names))

                        precision    recall  f1-score   support

           alt.atheism      1.000     0.971     0.985       480
         comp.graphics      0.937     1.000     0.968       584
               sci.med      1.000     0.970     0.985       594
soc.religion.christian      0.997     0.985     0.991       599

              accuracy                          0.982      2257
             macro avg      0.984     0.981     0.982      2257
          weighted avg      0.983     0.982     0.982      2257



In [210]:
print(classification_report(y_test, y_test_pred, digits=3, target_names=train_data.target_names))

                        precision    recall  f1-score   support

           alt.atheism      0.764     0.630     0.691       319
         comp.graphics      0.810     0.918     0.860       389
               sci.med      0.850     0.816     0.832       396
soc.religion.christian      0.787     0.827     0.806       398

              accuracy                          0.806      1502
             macro avg      0.803     0.798     0.797      1502
          weighted avg      0.805     0.806     0.803      1502

